const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const screens={title:'#titleScreen',creator:'#creatorScreen',draw:'#drawScreen',game:'#gameScreen'}; function show(k){$$('.screen').forEach(x=>x.classList.remove('active'));$(screens[k]).classList.add('active')}
$('#startBtn').onclick=()=>show('creator'); $$('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));
const cats=['body','skin','face','eyes','ears','hair','hat','armor','boots','weapon'];
const data={
body:[['Lean','lean','#445'],['Athletic','athletic','#445'],['Broad','broad','#445'],['Tall','tall','#445']],
skin:[['Warm','#e4a17a'],['Light','#f0c3a7'],['Deep','#8b533d'],['Dark','#563429'],['Lava','#e8623a'],['Ash','#aaa7a5']],
face:[['Soft','soft','#eee'],['Sharp','sharp','#eee'],['Round','round','#eee'],['Hero','hero','#eee'],['Demon','demon','#eee']],
eyes:[['Blue','blue','#3ca6ff'],['Green','green','#6ee26e'],['Gold','gold','#ffd83e'],['Red','red','#ff3f52'],['Void','void','#20193a'],['Cat','cat','#ffd83e']],
ears:[['Human','human','#eee'],['Pointed','pointed','#eee'],['Round','round','#eee'],['Demon','demon','#eee']],
hair:[['Spiky','spiky','#1f2230'],['Wild','wild','#ff5b27'],['Long','long','#202338'],['Mohawk','mohawk','#6c4cff'],['Flame','flame','#ff7b22'],['White','white','#eee'],['Blue','blue','#1f6fff']],
hat:[['None','none','#222'],['Headband','headband','#e33'],['Crown','crown','#ffd23f'],['Horns','horns','#3a2117'],['Tech Halo','halo','#58f3ff'],['Hood','hood','#2b243b']],
armor:[['Street','street','#39475d'],['Samurai','samurai','#a5332e'],['Tech','tech','#275d70'],['Bone','bone','#d8d0b8'],['Lava','lava','#7f2d1c'],['Royal','royal','#593b7b'],['Hunter','hunter','#4a5130']],
boots:[['Combat','combat','#202331'],['Stompers','stomp','#592819'],['Rockets','rocket','#2d5970'],['Claws','claw','#473226'],['Anime','anime','#7a2b30']],
weapon:[['Sword','sword','#dfe5ee'],['Axe','axe','#cfd7df'],['Hammer','hammer','#6f7581'],['Spear','spear','#d4dbe5'],['Katana','katana','#dce8f8'],['Blaster','blaster','#43e4ff']]
};
let sel={body:1,skin:0,face:3,eyes:0,ears:0,hair:0,hat:0,armor:2,boots:0,weapon:0},cat='body';
const catsEl=$('#cats'); cats.forEach(c=>{let b=document.createElement('button');b.textContent=c.toUpperCase();b.onclick=()=>{cat=c;renderOpts()};catsEl.appendChild(b)});
function itemName(x){return x[0]} function itemVal(x){return x[1]} function itemColor(x){return x[2]||x[1]}
function renderOpts(){[...catsEl.children].forEach((b,i)=>b.classList.toggle('active',cats[i]===cat));$('#optionTitle').textContent=cat.toUpperCase();let q=$('#search').value.toLowerCase();let g=$('#optionGrid');g.innerHTML='';data[cat].forEach((o,i)=>{if(!itemName(o).toLowerCase().includes(q))return;let b=document.createElement('button');b.className='opt'+(sel[cat]===i?' active':'');b.innerHTML=`<div class="swatch" style="background:${itemColor(o)}"></div><b>${itemName(o)}</b><small>${cat}</small>`;b.onclick=()=>{sel[cat]=i;renderOpts();renderAvatar()};g.appendChild(b)})}
$('#search').oninput=renderOpts; function renderAvatar(){const skin=itemVal(data.skin[sel.skin]),hair=itemColor(data.hair[sel.hair]),armor=itemColor(data.armor[sel.armor]);$$('.face,.ear,.neck,.arm').forEach(x=>x.style.background=skin);$('#hairBack').style.background=$('#hairFront').style.background=hair;$('#torso').style.background=armor;$('#face').style.borderRadius=['soft','sharp','round','hero','demon'][sel.face]==='round'?'50%':'48% 48% 44% 44%';let eye=itemColor(data.eyes[sel.eyes]);$$('.eye i').forEach(x=>x.style.background=eye);const hv=itemVal(data.hair[sel.hair]);$('#hairFront').style.clipPath=hv==='long'?'polygon(0 0,100% 0,100% 100%,70% 65%,52% 90%,35% 62%,0 100%)':hv==='mohawk'?'polygon(35% 0,48% 0,58% 100%,42% 100%)':hv==='wild'?'polygon(0 55%,12% 8%,28% 40%,43% 0,56% 42%,76% 5%,100% 58%,87% 100%,10% 100%)':'polygon(0 0,100% 0,92% 65%,75% 38%,61% 74%,47% 41%,30% 76%,17% 44%,0 71%)';let hat=itemVal(data.hat[sel.hat]),h=$('#hat');h.style.background='transparent';h.style.border='0';h.style.clipPath='none';if(hat==='headband'){h.style.background='#d33';h.style.height='15px';h.style.top='55px'} if(hat==='crown'){h.style.background='#ffd23f';h.style.clipPath='polygon(0 100%,0 40%,20% 65%,35% 0,52% 62%,72% 10%,100% 42%,100% 100%)'} if(hat==='horns'){h.style.borderLeft='22px solid transparent';h.style.borderRight='22px solid transparent';h.style.borderBottom='55px solid #3a2117'} if(hat==='halo'){h.style.border='7px solid #58f3ff';h.style.borderRadius='50%';h.style.height='26px';h.style.top='18px'} if(hat==='hood'){h.style.background='#2b243b';h.style.height='100px';h.style.borderRadius='50% 50% 15% 15%';h.style.zIndex='1'} let ev=itemVal(data.ears[sel.ears]);$$('.ear').forEach(x=>{x.style.borderRadius=ev==='pointed'?'60% 0 60% 60%':'50%';x.style.transform=ev==='pointed'?(x.classList.contains('l')?'rotate(-25deg)':'rotate(25deg)'):''});let bv=itemVal(data.body[sel.body]);let scale=bv==='broad'?1.08:bv==='lean'?.92:1;$('#torso').style.transform=`scaleX(${scale})`; let av=itemVal(data.armor[sel.armor]);$('#torso').style.clipPath=av==='samurai'?'polygon(0 10%,20% 0,80% 0,100% 10%,90% 100%,10% 100%)':av==='tech'?'polygon(20% 0,80% 0,100% 35%,78% 100%,22% 100%,0 35%)':'polygon(15% 0,85% 0,100% 20%,88% 100%,12% 100%,0 20%)'; let w=itemVal(data.weapon[sel.weapon]),pw=$('#previewWeapon');pw.style.width=w==='hammer'?'34px':'20px';pw.style.background=w==='blaster'?'#43e4ff':'linear-gradient(90deg,#777,#f4f4f4,#999)';pw.style.borderRadius=w==='blaster'?'8px':'10px'}
$('#randomBtn').onclick=()=>{cats.forEach(c=>sel[c]=Math.floor(Math.random()*data[c].length));renderOpts();renderAvatar()};$('#toDrawBtn').onclick=()=>show('draw');renderOpts();renderAvatar();
// drawing studio
const canv=$('#drawCanvas'),ctx=canv.getContext('2d');ctx.lineCap='round';ctx.lineJoin='round';ctx.fillStyle='#fff';ctx.fillRect(0,0,canv.width,canv.height);let drawColor='#111',drawing=false,last=null,undo=[],redo=[];const colors=['#111111','#ffffff','#ff3b30','#ff9500','#ffd60a','#34c759','#00c7be','#0a84ff','#5e5ce6','#bf5af2','#ff2d55','#8e5a2d','#7b7b7b','#e6a77f','#6b2f1a','#43e4ff'];let pal=$('#palette');pal.className='palette';colors.forEach((c,i)=>{let b=document.createElement('button');b.style.background=c;b.className=i===0?'active':'';b.onclick=()=>{drawColor=c;$$('#palette button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#eraserBtn').classList.remove('active')};pal.appendChild(b)});function snap(){undo.push(canv.toDataURL());if(undo.length>20)undo.shift();redo=[]}function pos(e){let r=canv.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canv.width/r.width,y:(p.clientY-r.top)*canv.height/r.height}}function down(e){e.preventDefault();snap();drawing=true;last=pos(e)}function move(e){if(!drawing)return;e.preventDefault();let p=pos(e);ctx.strokeStyle=drawColor;ctx.lineWidth=+$('#brushSize').value;ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}function up(){drawing=false}canv.addEventListener('pointerdown',down);canv.addEventListener('pointermove',move);canv.addEventListener('pointerup',up);canv.addEventListener('pointercancel',up);$('#eraserBtn').onclick=()=>{drawColor='#ffffff'};$('#clearDraw').onclick=()=>{snap();ctx.fillStyle='#fff';ctx.fillRect(0,0,700,700)};function restore(url){let im=new Image;im.onload=()=>ctx.drawImage(im,0,0);im.src=url}$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(canv.toDataURL());restore(undo.pop())};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(canv.toDataURL());restore(redo.pop())};
// THREE lazy load
let THREE=null;async function ensureThree(){if(THREE)return;await new Promise((ok,bad)=>{let s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.min.js';s.onload=ok;s.onerror=bad;document.head.appendChild(s)});THREE=window.THREE}
let scene,camera,renderer,player,monster,clock,anim,health=100,special=0,enemyHealth=100,meat=0,dead=false,won=false,blocking=false,enemyMode='hunt',enemyTimer=0,attackCd=0,dodgeCd=0,joy={x:0,y:0},yaw=0,pitch=0,drops=[];
function mat(c,e=0){return new THREE.MeshStandardMaterial({color:c,emissive:e,emissiveIntensity:e?0.35:0,roughness:.8})}function box(x,y,z,c,e=0){let m=new THREE.Mesh(new THREE.BoxGeometry(x,y,z),mat(c,e));m.castShadow=true;m.receiveShadow=true;return m}
function world(){scene.background=new THREE.Color(0x6a2616);scene.fog=new THREE.Fog(0x7b2b16,28,85);scene.add(new THREE.HemisphereLight(0xffd3a0,0x38110b,2.2));let dl=new THREE.DirectionalLight(0xffb36d,2.8);dl.position.set(8,16,12);scene.add(dl);let floor=box(34,.6,70,0x5a2a20);floor.position.y=-.3;scene.add(floor);for(let i=0;i<18;i++){let x=(Math.random()>.5?1:-1)*(8+Math.random()*7),z=-25+Math.random()*55;let r=box(2+Math.random()*3,1+Math.random()*5,2+Math.random()*3,0x3d1b16);r.position.set(x,r.geometry.parameters.height/2,z);scene.add(r)}for(let i=0;i<6;i++){let lava=box(2.5+Math.random()*3,.15,9+Math.random()*6,0xff5a12,0xff2a00);lava.position.set((Math.random()-.5)*20,.12,-24+i*10);scene.add(lava);let pl=new THREE.PointLight(0xff6a24,2.2,12);pl.position.set(lava.position.x,1.2,lava.position.z);scene.add(pl)}for(let i=0;i<45;i++){let ember=box(.09,.09,.09,0xffd36a,0xff8a1f);ember.position.set((Math.random()-.5)*28,1+Math.random()*8,-28+Math.random()*60);scene.add(ember)}for(let i=0;i<5;i++){let pillar=box(2,6+Math.random()*6,2,0x2c1714);pillar.position.set((i%2?1:-1)*(10+Math.random()*3),pillar.geometry.parameters.height/2,-18+i*10);scene.add(pillar)}}
function monsterSprite(){let tex=new THREE.CanvasTexture(canv);tex.colorSpace=THREE.SRGBColorSpace;let sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true}));sp.scale.set(6,6,1);let g=new THREE.Group();g.add(sp);let glow=new THREE.PointLight(0xff5a24,4,12);glow.position.set(0,1,0);g.add(glow);let weapon=box(.25,3.8,.25,0x222222);weapon.position.set(2.4,0,0);weapon.rotation.z=.55;g.add(weapon);g.position.set(0,3,-18);scene.add(g);return g}
function init(){cancelAnimationFrame(anim);$('#gameCanvas').innerHTML='';health=100;special=0;enemyHealth=100;dead=won=blocking=false;enemyMode='hunt';enemyTimer=1;attackCd=dodgeCd=0;joy={x:0,y:0};yaw=pitch=0;drops=[];scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.1,120);player=new THREE.Object3D();player.position.set(0,1.7,18);player.add(camera);scene.add(player);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);$('#gameCanvas').appendChild(renderer.domElement);world();monster=monsterSprite();clock=new THREE.Clock();$('#death').classList.add('hidden');$('#victory').classList.add('hidden');$('#message').textContent='Your drawing is somewhere ahead. It is coming for you.';setupLook();update();loop()}
function setupLook(){let c=renderer.domElement,drag=false,lx=0,ly=0;c.onpointerdown=e=>{if(e.clientX<innerWidth*.38)return;drag=true;lx=e.clientX;ly=e.clientY};c.onpointermove=e=>{if(!drag)return;let dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.005;pitch=Math.max(-.5,Math.min(.5,pitch-dy*.004));player.rotation.y=yaw;camera.rotation.x=pitch};c.onpointerup=c.onpointercancel=()=>drag=false}
function dist(){return player.position.distanceTo(monster.position)}function facing(){let f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion).normalize(),d=monster.position.clone().sub(player.position).setY(0).normalize();return f.dot(d)>.35}
function update(){$('#healthText').textContent=Math.round(health);$('#healthBar').style.width=health+'%';$('#specialText').textContent=Math.round(special)+'%';$('#specialBar').style.width=special+'%';$('#enemyBar').style.width=Math.max(0,enemyHealth)+'%';$('#specialBtn').disabled=special<100||dead||won;$('#meatCount').textContent=$('#invMeat').textContent=meat}
function attack(s=false){if(dead||won||attackCd>0)return;if(s&&special<100)return;attackCd=s?.7:.35;$('#heldWeapon').classList.add('swing');setTimeout(()=>$('#heldWeapon').classList.remove('swing'),280);if(s)special=0;if(dist()<5.2&&facing()){let dmg=s?48:18;enemyHealth-=dmg;if(!s)special=Math.min(100,special+14);$('#message').textContent=s?'MEGA SPECIAL!':'HIT!';if(enemyHealth<=0)kill()}else $('#message').textContent='GET CLOSER AND AIM AT IT';update()}
function enemy(dt){if(dead||won)return;let d=dist(),dir=player.position.clone().sub(monster.position);dir.y=0;if(enemyMode==='hunt'){let speed=d>10?2.7:d>5?3.4:1.4;monster.position.addScaledVector(dir.normalize(),dt*speed);enemyTimer-=dt;if(d<4.3&&enemyTimer<=0){enemyMode='windup';enemyTimer=.75;$('#warning').classList.remove('hidden');$('#message').textContent='BLOCK OR DODGE!';monster.scale.set(1.15,1.15,1)}}else if(enemyMode==='windup'){enemyTimer-=dt;if(enemyTimer<=0){$('#warning').classList.add('hidden');if(d<4.7){let hit=blocking?4:19;health=Math.max(0,health-hit);$('#message').textContent=blocking?'BLOCKED! + SPECIAL':'SMASHED!';if(blocking)special=Math.min(100,special+14)}else $('#message').textContent='NICE DODGE!';monster.scale.set(1,1,1);enemyMode='recover';enemyTimer=.55;if(health<=0){dead=true;$('#death').classList.remove('hidden')}update()}}else{enemyTimer-=dt;if(enemyTimer<=0){enemyMode='hunt';enemyTimer=1.0+Math.random()*.45}}}
function kill(){enemyHealth=0;won=true;monster.visible=false;for(let i=0;i<2;i++){let m=box(.7,.35,.45,0xb72c1f,0x5d0900);m.position.copy(monster.position).add(new THREE.Vector3(i?1:-1,.3,0));scene.add(m);drops.push(m)}$('#message').textContent='MONSTER DOWN — COLLECT THE MEAT';update()}
function collect(){for(let i=drops.length-1;i>=0;i--){let d=drops[i];d.rotation.y+=.04;if(player.position.distanceTo(d.position)<1.7){scene.remove(d);drops.splice(i,1);meat++;special=Math.min(100,special+10);$('#message').textContent='🥩 EMBER MEAT COLLECTED';update()}}if(won&&drops.length===0&&!$('#victory').dataset.shown){$('#victory').dataset.shown='1';$('#victory').classList.remove('hidden')}}
function loop(){anim=requestAnimationFrame(loop);let dt=Math.min(clock.getDelta(),.05);attackCd=Math.max(0,attackCd-dt);dodgeCd=Math.max(0,dodgeCd-dt);if(!dead){let f=new THREE.Vector3(0,0,-1).applyQuaternion(player.quaternion);f.y=0;f.normalize();let r=new THREE.Vector3(1,0,0).applyQuaternion(player.quaternion);r.y=0;r.normalize();player.position.addScaledVector(r,joy.x*6.2*dt);player.position.addScaledVector(f,-joy.y*6.2*dt);player.position.x=Math.max(-15,Math.min(15,player.position.x));player.position.z=Math.max(-30,Math.min(24,player.position.z));enemy(dt);collect()}renderer.render(scene,camera)}
// joystick
const joyEl=$('#joy'),knob=$('#joyKnob');let joyId=null;function joyMove(e){let r=joyEl.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=e.clientX-cx,dy=e.clientY-cy,max=r.width*.32,len=Math.hypot(dx,dy)||1;if(len>max){dx=dx/len*max;dy=dy/len*max}joy.x=dx/max;joy.y=dy/max;knob.style.transform=`translate(${dx}px,${dy}px)`}joyEl.onpointerdown=e=>{joyId=e.pointerId;joyEl.setPointerCapture(e.pointerId);joyMove(e)};joyEl.onpointermove=e=>{if(e.pointerId===joyId)joyMove(e)};joyEl.onpointerup=joyEl.onpointercancel=e=>{if(e.pointerId!==joyId)return;joyId=null;joy={x:0,y:0};knob.style.transform='translate(0,0)'};
$('#attackBtn').onclick=()=>attack(false);$('#specialBtn').onclick=()=>attack(true);$('#blockBtn').onpointerdown=()=>blocking=true;$('#blockBtn').onpointerup=$('#blockBtn').onpointercancel=()=>blocking=false;$('#dodgeBtn').onclick=()=>{if(dodgeCd>0||dead)return;dodgeCd=1;let r=new THREE.Vector3(1,0,0).applyQuaternion(player.quaternion);player.position.addScaledVector(r,Math.random()>.5?3.2:-3.2);$('#message').textContent='DODGE!'};$('#inventoryBtn').onclick=()=>$('#inventory').classList.toggle('hidden');$('#invClose').onclick=()=>$('#inventory').classList.add('hidden');$('#eatBtn').onclick=()=>{if(!meat)return;meat--;health=Math.min(100,health+30);special=Math.min(100,special+25);update()};$('#retryBtn').onclick=()=>{delete $('#victory').dataset.shown;init()};$('#againBtn').onclick=()=>{delete $('#victory').dataset.shown;init()};$('#deathCreator').onclick=()=>show('creator');$('#deathMenu').onclick=()=>show('title');$('#victoryDraw').onclick=()=>show('draw');$('#victoryMenu').onclick=()=>show('title');$('#enterBtn').onclick=async()=>{let b=$('#enterBtn');b.disabled=true;b.textContent='OPENING NETHEN…';try{await ensureThree();show('game');setTimeout(init,50)}catch(e){alert('3D world could not load. Check the internet and try again.')}finally{b.disabled=false;b.textContent='ENTER THE NETHEN →'}};addEventListener('resize',()=>{if(!renderer)return;camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
